public class Datatypes {
    public static void main(String[] args){
    int num = 94;
    float num2 = 43.3F;
    double num3 =3.2;
    char hello = 'e';
    String ja = "helllow";
    boolean hai = true;
    long hu =324243243424234243l;
//==========================================================
    System.out.println(num); //-->For Printing
    System.out.println(num2); //-->For Printing
    System.out.println(num3); //-->For Printing
    System.out.println(hello); //-->For Printing
    System.out.println(ja); //-->For Printing
    System.out.println(hai); //-->For Printing
    System.out.println(hu); //-->For Printing
}
}
